application {
  name = "proteus-benchmark"
  version = "0.9.5"
  host = "0.0.0.0"
  path = ""
  ports {
    http = 21080
  }
}

globalHeaders {
  Server = "proteus"
}

undertow {
  server {
    recordRequestStartTime = false
  }
}
