/**
 * Simple, working Modern HandlerGenerator for unit testing
 */
package io.sinistral.proteus.server.handlers.modern;

import io.sinistral.proteus.server.handlers.HandlerGenerator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

/**
 * Simplified modern handler generator that actually works.
 * Focus on basic functionality first, then add advanced features.
 */
public class SimpleModernHandlerGenerator extends HandlerGenerator {
    
    private static final Logger log = LoggerFactory.getLogger(SimpleModernHandlerGenerator.class);
    
    // Simple cache for testing
    private static final ConcurrentMap<String, String> SIMPLE_CACHE = new ConcurrentHashMap<>();
    
    private final ModernHandlerConfig config;
    
    public SimpleModernHandlerGenerator(String packageName, Class<?> controllerClass, ModernHandlerConfig config) {
        super(packageName, controllerClass);
        this.config = config;
    }
    
    @Override
    public String generateClassSource() throws Exception {
        // Check cache if enabled
        if (config.isEnableCaching()) {
            String cacheKey = controllerClass.getName();
            String cached = SIMPLE_CACHE.get(cacheKey);
            if (cached != null) {
                return cached;
            }
        }
        
        // Generate the source
        String originalSource = super.generateClassSource();
        
        // Add modern header
        String modernSource = addModernHeader(originalSource);
        
        // Cache if enabled
        if (config.isEnableCaching()) {
            SIMPLE_CACHE.put(controllerClass.getName(), modernSource);
        }
        
        return modernSource;
    }
    
    private String addModernHeader(String originalSource) {
        String modernHeader = """
                /*
                 * GENERATED CODE - DO NOT EDIT (Modern Version)
                 * 
                 * This file was generated by Proteus Modern HandlerGenerator
                 * Generation time: %s
                 * Java version: %s
                 * Features enabled:
                 * - Modern Header: enabled
                 * - Caching: %s
                 * - Debug: %s
                 */
                
                """.formatted(
                java.time.Instant.now(),
                System.getProperty("java.version"),
                config.isEnableCaching() ? "enabled" : "disabled",
                config.isDebugMode() ? "enabled" : "disabled"
        );
        
        return modernHeader + originalSource;
    }
    
    // Simple static methods for testing
    public static Map<String, Object> getMetrics() {
        Map<String, Object> metrics = new HashMap<>();
        metrics.put("cache_size", SIMPLE_CACHE.size());
        return metrics;
    }
    
    public static void clearCache() {
        SIMPLE_CACHE.clear();
        log.info("Simple handler cache cleared");
    }
}
