/**
 * Simple, working Modern HandlerGenerator for unit testing
 */
package io.sinistral.proteus.server.handlers.modern;

import io.sinistral.proteus.server.handlers.HandlerGenerator;
import io.sinistral.proteus.server.handlers.modern.cache.HandlerCache;
import io.sinistral.proteus.server.handlers.modern.cache.HandlerCacheFactory;
import io.sinistral.proteus.server.handlers.modern.cache.CacheMetrics;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

/**
 * Simplified modern handler generator that actually works.
 * Focus on basic functionality first, then add advanced features.
 */
public class SimpleModernHandlerGenerator extends HandlerGenerator {
    
    private static final Logger log = LoggerFactory.getLogger(SimpleModernHandlerGenerator.class);
    
    // Modern cache system
    private final HandlerCache cache;
    private final ModernHandlerConfig config;
    
    public SimpleModernHandlerGenerator(String packageName, Class<?> controllerClass, ModernHandlerConfig config) {
        super(packageName, controllerClass);
        this.config = config;
        
        // Initialize cache based on config
        if (config.isEnableCaching()) {
            this.cache = HandlerCacheFactory.createLRUWithTTL(
                config.getMaxCacheSize(),
                config.getCacheTimeout()
            );
        } else {
            this.cache = null;
        }
    }
    
    @Override
    public String generateClassSource() throws Exception {
        // Use cache if enabled
        if (config.isEnableCaching() && cache != null) {
            String cacheKey = controllerClass.getName();
            Object result = cache.computeIfAbsent(cacheKey, this::doGenerateClassSource);
            return (String) result;
        }
        
        return doGenerateClassSource(controllerClass.getName());
    }
    
    private String doGenerateClassSource(String cacheKey) {
        try {
            // Generate the source
            String originalSource = super.generateClassSource();
            
            // Add modern header
            return addModernHeader(originalSource);
        } catch (Exception e) {
            log.error("Failed to generate handler source for: {}", cacheKey, e);
            throw new RuntimeException("Handler generation failed", e);
        }
    }
    
    private String addModernHeader(String originalSource) {
        String modernHeader = """
                /*
                 * GENERATED CODE - DO NOT EDIT (Modern Version)
                 * 
                 * This file was generated by Proteus Modern HandlerGenerator
                 * Generation time: %s
                 * Java version: %s
                 * Features enabled:
                 * - Modern Header: enabled
                 * - Caching: %s
                 * - Debug: %s
                 */
                
                """.formatted(
                java.time.Instant.now(),
                System.getProperty("java.version"),
                config.isEnableCaching() ? "enabled" : "disabled",
                config.isDebugMode() ? "enabled" : "disabled"
        );
        
        return modernHeader + originalSource;
    }
    
    // Instance methods for cache management
    public Map<String, Object> getMetrics() {
        Map<String, Object> metrics = new HashMap<>();
        
        if (cache != null) {
            Optional<CacheMetrics> cacheMetrics = cache.getMetrics();
            if (cacheMetrics.isPresent()) {
                CacheMetrics cm = cacheMetrics.get();
                metrics.put("cache_size", cm.getSize());
                metrics.put("cache_hits", cm.getHits());
                metrics.put("cache_misses", cm.getMisses());
                metrics.put("hit_rate", cm.getHitRate());
                metrics.put("evictions", cm.getEvictions());
                metrics.put("avg_load_time_ms", cm.getAverageLoadTime() / 1_000_000.0);
            } else {
                metrics.put("cache_size", cache.size());
            }
        } else {
            metrics.put("cache_size", 0);
            metrics.put("cache_enabled", false);
        }
        
        return metrics;
    }
    
    public void clearCache() {
        if (cache != null) {
            cache.clear();
            log.info("Modern handler cache cleared");
        }
    }
    
    public void shutdown() {
        if (cache != null) {
            cache.shutdown();
            log.info("Modern handler generator shutdown completed");
        }
    }
}
