<?xml version="1.0" encoding="UTF-8" ?>
<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
>
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.sinistral</groupId>
        <artifactId>proteus-project</artifactId>
        <version>0.9.5-SNAPSHOT</version>
    </parent>

    <artifactId>proteus-websocket</artifactId>
    <packaging>jar</packaging>
    <name>Proteus WebSocket</name>

    <description>Undertow WebSocket endpoint handling for Proteus applications.</description>

    <dependencies>

        <dependency>
            <groupId>io.sinistral</groupId>
            <artifactId>proteus-core</artifactId>
        </dependency>

        <dependency>
            <groupId>io.undertow</groupId>
            <artifactId>undertow-websockets-jsr</artifactId>
            <version>${undertow.version}</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
            <version>${hamcrest.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

</project>
